"""Generate the rebuilt JOKER_CATALOGUE (canonical keys, real rarity + cost)
and the canonical->legacy registry alias map, straight from balatro-rs's
authoritative joker_data! table. Writes:
  tools/out_joker_catalogue.py  — replacement dict for shop.py
  tools/out_joker_aliases.py    — alias block for jokers/__init__.py
"""
import re
import sys

sys.path.insert(0, "vendor/balatro-rl")
from balatro_sim.shop import JOKER_CATALOGUE
from balatro_sim.jokers.base import JOKER_REGISTRY

# ── parse joker_data! ────────────────────────────────────────────────────────
rows = []
text = open("vendor/balatro-rs/balatro-types/src/joker.rs", encoding="utf-8", errors="replace").read()
for m in re.finditer(
    # \s* between name and rarity: most rows are '"Name",   Rarity' but a few
    # are '"Name",Rarity' (e.g. Delayed Gratification) — tolerate both so no
    # real joker is dropped from the catalogue.
    r'(\w+),\s+"(j_[a-z0-9_]+)",\s+"([^"]+)",\s*(\w+)\s*,\s*(\d+)',
    text,
):
    rows.append((m.group(2), m.group(3), m.group(4).capitalize(), int(m.group(5))))

# ── legacy effect key per real joker ─────────────────────────────────────────
# Sim catalogue key (name-matched) for jokers currently offered.
def norm(s):
    return re.sub(r"[^a-z0-9]", "", s.lower())

sim_by_name = {}
for key, info in JOKER_CATALOGUE.items():
    sim_by_name.setdefault(norm(info["name"]), key)

# Known legacy REGISTRY keys for jokers with no catalogue entry (M1 triage).
LEGACY_UNOFFERED = {
    "j_mail": "j_mail_in_rebate", "j_stone": "j_stone_joker",
    "j_ticket": "j_golden_ticket", "j_idol": "j_the_idol",
    "j_to_the_moon": "j_to_the_moon", "j_hallucination": "j_hallucination",
    "j_fortune_teller": "j_fortune_teller", "j_juggler": "j_juggler",
    "j_drunkard": "j_drunkard", "j_golden": "j_golden", "j_smiley": "j_smiley",
    "j_bootstraps": "j_bootstraps", "j_caino": "j_caino",
}

def legacy_key(canonical_id, real_name):
    n = norm(real_name)
    skey = sim_by_name.get(n)
    if skey is not None and skey in JOKER_REGISTRY:
        return skey
    return LEGACY_UNOFFERED.get(canonical_id)

# ── build the alias map ──────────────────────────────────────────────────────
aliases = {}
for cid, cname, rar, cost in rows:
    leg = legacy_key(cid, cname)
    if cid in JOKER_REGISTRY:
        # resolves natively — but check for wrong-effect collisions (j_ticket)
        if leg is not None and leg != cid and JOKER_REGISTRY[leg] is not JOKER_REGISTRY[cid]:
            aliases[cid] = leg
        continue
    if leg is None:
        print(f"WARNING: no legacy effect found for {cid} ({cname})")
        continue
    aliases[cid] = leg

# Canonical keys that ALREADY resolve natively must stay native, except these
# deliberate overrides (the natively-registered class is stale/wrong for the
# canonical id).
DELIBERATE_OVERRIDES = {
    "j_ring_master": "j_showman",    # real id of Showman; marker must not shadow
    "j_ticket": "j_golden_ticket",   # scaling._Ticket is not the real effect
    # j_wee resolves natively (misc._Wee, the permanent +8-chips-per-2 build);
    # the old j_wee -> j_wee_joker override pointed at a flat +8-per-hand build.
    # real id is misspelled "gluttenous"; the sim's native key corrects it.
    "j_gluttenous_joker": "j_gluttonous_joker",
}
for canon, legacy in DELIBERATE_OVERRIDES.items():
    if legacy in JOKER_REGISTRY:
        aliases[canon] = legacy
# Native per-card registrations (j_greedy_joker -> _Greedy, etc.) must win over
# the legacy catalogue keys they were previously aliased to.
for canon in ("j_greedy_joker", "j_lusty_joker", "j_wrathful_joker"):
    if canon in JOKER_REGISTRY:
        aliases.pop(canon, None)

# ── emit catalogue ───────────────────────────────────────────────────────────
with open("tools/out_joker_catalogue.py", "w", encoding="utf-8") as f:
    f.write("# Generated by tools/gen_joker_catalogue.py from balatro-rs joker_data!\n")
    f.write("# Canonical real-game ids, real rarities, real base costs (wiki-verified).\n")
    f.write("JOKER_CATALOGUE: dict[str, dict] = {\n")
    for cid, cname, rar, cost in rows:
        f.write(f'    "{cid}": {{"key": "{cid}", "name": "{cname}", '
                f'"rarity": "{rar}", "price": {cost}}},\n')
    f.write("}\n")

# ── emit aliases ─────────────────────────────────────────────────────────────
with open("tools/out_joker_aliases.py", "w", encoding="utf-8") as f:
    f.write("# Generated by tools/gen_joker_catalogue.py — canonical real-game ids that\n")
    f.write("# resolve to the sim's legacy effect classes.\n")
    f.write("_CANONICAL_JOKER_ALIASES = {\n")
    for cid in sorted(aliases):
        f.write(f'    "{cid}": "{aliases[cid]}",\n')
    f.write("}\n")

print(f"rows: {len(rows)}  catalogue entries: {len(rows)}  aliases: {len(aliases)}")
missing_effects = [cid for cid, _, _, _ in rows if cid not in JOKER_REGISTRY and cid not in aliases]
print("real jokers with NO resolvable effect:", missing_effects)
print("aliases:", aliases)
