<#
iterate.ps1 — one command for the learn -> collect -> fit -> audit loop.

WHY THIS EXISTS
===============
The coverage gap is measured in *rows*, and one iteration of the loop costs
~55 minutes at 12 workers. Every stage of that loop already exists as a tool;
what was missing was a single entry point that runs them in the right order,
keeps the work order in sync with the freshly fitted model, and leaves a
ledger entry so a later reader can see what was run and what it produced.

WHY IT IS RESUMABLE (read this before changing the order)
========================================================
The first overnight run of this script collected 2,766 rows and then stopped
between the collect and fit stages. Nothing downstream existed: no fit, no work
order, no ledger line, no screen — and the surviving evidence of *where* it
stopped was a log file with no closing summary. A one-shot script makes an
interrupted run indistinguishable from a run that never started.

So: every stage declares an artifact, and a stage whose artifact already exists
is SKIPPED unless -Force is passed. A crash, a reboot, a closed terminal or an
Orchestrator restart therefore costs at most one stage, and re-running the same
command resumes instead of restarting. The ledger gets a line per stage as it
happens (not one line at the end), and a heartbeat file records the last stage
that started, so "what was it doing when it died" is answerable.

CORPUS HYGIENE
==============
The fit consumes every non-empty `results/decisions/{train,holdout}_*.jsonl`
except `*smoke*` (throwaway dev rows live in `results/decisions/_dev/`). Adding
a new iteration therefore needs no edit here — drop the file in and the next
round picks it up.

SEED RANGES ALREADY COLLECTED (do not overlap)
==============================================
  40000-40159  v1      41000-41149  v2      41200-41499  v3 (partial)
  42000-42499  v4      43000-43099  v5      44000-44xxx  v6
  45000-46xxx  iter1   50000-50199  offer census
  `-SeedStart` defaults to 47000, past everything above.

THE LOOP (one iteration)
========================
  1. census   (every N) rewrite which cells are considered fillable, so budget
              follows items the agent is actually offered.
  2. audit    re-score the scenario grid against the CURRENT artifact and write
              the next work order (cells short of `required_n` own rows).
  3. collect  fork-and-rollout collection aimed at that work order.
  4. fit      refit the linear head + residual cells on ALL iterations to date,
              holding the seed-keyed holdout out.
  5. audit    regenerate the work order for the next iteration from the refit.
  6. screen   (optional) paired small-seed screen of the oracle arms against
              frozen V10, so the loop reports behaviour, not just coverage.

WHY THE STAGES ARE IN THIS ORDER
================================
Collection targets a work order generated by the *previous* fit, so the work
order can never describe a model the data has already moved past.

ATTACH A NEXT ACTION, ALWAYS
============================
Each stage appends a JSON line to logs_sim/runs.jsonl carrying its metrics and
an explicit `next` field. A run that cannot say what should happen next is how a
loop becomes a ritual.

USAGE
=====
    # 3 iterations, 55 min each, 12 workers, with a 100-seed screen per round
    powershell -NoProfile -ExecutionPolicy Bypass -File tools/iterate.ps1 -Iterations 3

    # one long unattended night: 8 iterations, no screen (collection only)
    powershell -NoProfile -ExecutionPolicy Bypass -File tools/iterate.ps1 `
        -Iterations 8 -BudgetMinutes 55 -SkipScreen

    # re-run the same command after an interruption: finished stages are skipped
    powershell -NoProfile -ExecutionPolicy Bypass -File tools/iterate.ps1 -Iterations 8 -SkipScreen

    # detached, so a launcher that dies takes nothing with it
    powershell -NoProfile -ExecutionPolicy Bypass -File tools/iterate.ps1 `
        -Iterations 8 -SkipScreen -Detached

PARAMETERS
==========
  -Iterations         how many collect->fit cycles (default 3)
  -SeedStart          first seed of iteration 1; each iteration advances by
                      -SeedStride so no seed is collected twice
  -SeedsPerIteration  seed pool offered per iteration (budget usually stops it)
  -BudgetMinutes      collection wall-clock budget per iteration (default 55)
  -Workers            parallel collection workers (default 12 = leave 4 cores
                      free, so development work can continue during a run)
  -ScreenSeeds        seeds in the per-iteration paired screen (default 100;
                      0 disables it)
  -Variants           comma-separated ablation arms for the screen
  -CensusEvery        re-run the offer census every N iterations (default 2)
  -SkipScreen         collection + fit only
  -Force              ignore existing artifacts and redo every stage
  -Detached           relaunch hidden and return immediately
  -CandidateMode      coverage | onpolicy (default onpolicy)
  -Tag                prefix for result files (default "iter")
#>
param(
    [int]$Iterations = 3,
    [int]$SeedStart = 47000,
    [int]$SeedStride = 1000,
    [int]$SeedsPerIteration = 500,
    [double]$BudgetMinutes = 55,
    [int]$Workers = 12,
    [int]$ScreenSeeds = 100,
    [string]$Variants = "v12_prior_m0,v12_prior_m05,v12_rel_z2",
    [int]$CensusEvery = 2,
    [switch]$SkipScreen,
    [switch]$Force,
    [switch]$Detached,
    [string]$CandidateMode = "onpolicy",
    [string]$Tag = "iter"
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root
$LogDir = Join-Path $Root "logs_sim"
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
$Heartbeat = Join-Path $LogDir "$Tag`_heartbeat.txt"
$StateFile = Join-Path $LogDir "$Tag`_state.json"

if ($Detached) {
    $argList = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File',
                 (Join-Path $PSScriptRoot 'iterate.ps1'),
                 '-Iterations', "$Iterations", '-SeedStart', "$SeedStart",
                 '-SeedStride', "$SeedStride",
                 '-SeedsPerIteration', "$SeedsPerIteration",
                 '-BudgetMinutes', "$BudgetMinutes", '-Workers', "$Workers",
                 '-ScreenSeeds', "$ScreenSeeds", '-Variants', $Variants,
                 '-CensusEvery', "$CensusEvery", '-CandidateMode', $CandidateMode,
                 '-Tag', $Tag)
    if ($SkipScreen) { $argList += '-SkipScreen' }
    if ($Force) { $argList += '-Force' }
    $out = Join-Path $LogDir "$Tag`_main.log"
    $err = Join-Path $LogDir "$Tag`_main.err"
    Start-Process powershell -ArgumentList $argList -WindowStyle Hidden `
        -RedirectStandardOutput $out -RedirectStandardError $err | Out-Null
    Write-Host "iterate.ps1 detached -> $out (heartbeat $Heartbeat)"
    exit 0
}

function Write-Heartbeat {
    param([string]$Stage, [string]$Status)
    # BOM-free writes: this machine's PowerShell is 5.1, where ConvertFrom-Json
    # chokes on a BOM and Set-Content -Encoding UTF8 adds one.
    $line = "{0}`t{1}`t{2}`t{3}" -f (Get-Date).ToString("s"), $Stage, $Status, $PID
    try { [System.IO.File]::WriteAllText($Heartbeat, $line) } catch { }
    try {
        $state = [ordered]@{ stage = $Stage; status = $Status
                             updated = (Get-Date).ToString("s"); pid = $PID }
        [System.IO.File]::WriteAllText(
            $StateFile, ($state | ConvertTo-Json -Compress))
    } catch { }
}

function Add-Ledger {
    param([hashtable]$Entry)
    $path = Join-Path $LogDir "runs.jsonl"
    if (-not $Entry.ContainsKey("started")) {
        $Entry["started"] = (Get-Date).ToString("s")
    }
    $json = ($Entry | ConvertTo-Json -Compress -Depth 6)
    Add-Content -Path $path -Value $json -Encoding UTF8
}

function Test-Artifact {
    param([string]$Path)
    if (-not $Path) { return $false }
    $full = Join-Path $Root $Path
    if (-not (Test-Path $full)) { return $false }
    $item = Get-Item $full
    if ($item.PSIsContainer) { return $true }
    if ($item.Length -le 0) { return $false }
    # A log written but never closed can survive a kill at size > 0; for JSON
    # artifacts insist on parseable content so a truncated fit is not "done".
    if ($item.Extension -eq ".json") {
        try { Get-Content $full -Raw | ConvertFrom-Json | Out-Null; return $true }
        catch { return $false }
    }
    return $true
}

function Invoke-Stage {
    param(
        [string]$Name,
        [string[]]$Command,
        [string]$SkipIf,          # artifact path relative to $Root
        [string]$Next = "",
        [hashtable]$Extra = @{}
    )
    $log = Join-Path $LogDir "$Tag`_$Name.log"
    if ($SkipIf -and -not $Force -and (Test-Artifact -Path $SkipIf)) {
        Write-Host "[$Tag/$Name] SKIP (artifact exists: $SkipIf)"
        Add-Ledger -Entry (@{
            id = "$Tag-$Name"; kind = "iterate-stage"; stage = $Name
            command = ($Command -join ' ')
            result = "skipped: artifact already present ($SkipIf)"
            artifact = $SkipIf; next = $Next
        })
        return $log
    }

    Write-Host ""
    Write-Host ("=" * 72)
    Write-Host "[$Tag/$Name] $($Command -join ' ')"
    Write-Host ("=" * 72)
    Write-Heartbeat -Stage $Name -Status "running"
    $t0 = Get-Date
    $code = 0
    try {
        # Tee so the console shows progress AND the log keeps it.
        & $Command[0] @($Command[1..($Command.Length - 1)]) 2>&1 |
            Tee-Object -FilePath $log
        $code = $LASTEXITCODE
        if ($null -eq $code) { $code = 0 }
    } catch {
        $code = 1
        Write-Host "[$Tag/$Name] EXCEPTION: $_"
        Add-Content -Path $log -Value "EXCEPTION: $_" -Encoding UTF8
    }
    $mins = [math]::Round(((Get-Date) - $t0).TotalMinutes, 1)
    Write-Host "[$Tag/$Name] exit=$code in ${mins}m -> $log"

    $entryArgs = @{ id = "$Tag-$Name"; kind = "iterate-stage"; stage = $Name }
    foreach ($k in $Extra.Keys) { $entryArgs[$k] = $Extra[$k] }
    $entryArgs["command"] = ($Command -join ' ')
    $entryArgs["minutes"] = $mins
    # PowerShell 5.1 has no if-expression, so branches are assigned explicitly.
    if ($code -eq 0) { $entryArgs["result"] = "ok" }
    else { $entryArgs["result"] = "FAILED exit=$code (see $log)" }
    if ($SkipIf) { $entryArgs["artifact"] = $SkipIf } else { $entryArgs["artifact"] = "" }
    $entryArgs["next"] = $Next
    Add-Ledger -Entry $entryArgs

    if ($code -ne 0) {
        Write-Heartbeat -Stage $Name -Status "failed"
        Write-Host ""
        Write-Host "[$Tag/$Name] FAILED after ${mins}m. Resume by re-running the same"
        Write-Host "command: completed stages are skipped. Log: $log"
        throw "[$Tag/$Name] failed with exit code $code"
    }
    Write-Heartbeat -Stage $Name -Status "ok"
    return $log
}

function Get-DecisionFiles {
    param([string]$Split)
    # Auto-discovery, with the throwaway smoke corpora excluded: a fit that
    # silently absorbs hand-made dev rows is how "measured" stops meaning
    # anything. Dev rows live in results/decisions/_dev/ (never matched by this
    # glob) and any *smoke* file left in the main directory is skipped
    # explicitly.
    $glob = Join-Path $Root "results/decisions/$Split`_*.jsonl"
    $files = Get-ChildItem -Path $glob -ErrorAction SilentlyContinue |
        Where-Object { $_.Length -gt 0 -and $_.Name -notlike "*smoke*" } |
        Sort-Object Name
    if (-not $files) { throw "no non-empty $Split files matched $glob" }
    Write-Host "[$Split corpus] $($files.Count) file(s): $($files.Name -join ', ')"
    return ($files | ForEach-Object { $_.FullName }) -join ","
}

# --- report how a previous run ended, before doing anything -----------------
if (Test-Path $Heartbeat) {
    $prev = (Get-Content $Heartbeat -Raw).Trim()
    Write-Host "previous run heartbeat: $prev"
}
if (Test-Path $StateFile) {
    try {
        $st = Get-Content $StateFile -Raw | ConvertFrom-Json
        if ($st.status -eq "running") {
            Write-Host "NOTE: a previous run was interrupted mid-stage ('$($st.stage)')."
            Write-Host "      Finished stages will be skipped; re-running resumes there."
        }
    } catch { }
}

Write-Host "iterate.ps1 | root=$Root | iterations=$Iterations | workers=$Workers | force=$Force"
Write-Host "seed start=$SeedStart stride=$SeedStride | budget=${BudgetMinutes}m | screen=$ScreenSeeds seeds [$Variants]"

for ($i = 1; $i -le $Iterations; $i++) {
    $itTag = "$Tag$i"
    $seed0 = $SeedStart + ($i - 1) * $SeedStride

    # --- census (rewrites which cells are fillable) ---------------------------
    if ($CensusEvery -gt 0 -and ($i -eq 1 -or ($i % $CensusEvery) -eq 0)) {
        Invoke-Stage -Name "${itTag}_census" -SkipIf "results/offer_census.json" -Command @(
            "python", "tools/offer_census.py",
            "--seed-start", "$(50000 + 500 * $i)", "--n-seeds", "200",
            "--workers", "$Workers", "--out", "results/offer_census.json") `
            -Next "offer census feeds the coverage audit's fillable set; rerun if the agent's offer mix changes" | Out-Null
    }

    # --- 1. work order from the current artifact -----------------------------
    Invoke-Stage -Name "${itTag}_audit_pre" -SkipIf "results/coverage_focus_$itTag.json" -Command @(
        "python", "tools/audit_value_coverage.py",
        "--census", "results/offer_census.json",
        "--focus-out", "results/coverage_focus_$itTag.json") `
        -Next "collect against this work order; audit_post regenerates it from the refit" | Out-Null

    # --- 2. coverage-targeted collection ------------------------------------
    Invoke-Stage -Name "${itTag}_collect" -SkipIf "results/decisions/train_$itTag.jsonl" -Command @(
        "python", "tools/collect_decisions.py",
        "--seed-start", "$seed0",
        "--n-seeds", "$SeedsPerIteration",
        "--time-budget-min", "$BudgetMinutes",
        "--workers", "$Workers",
        "--focus-file", "results/coverage_focus_$itTag.json",
        "--focus-extra", "3",
        # onpolicy by default: it forks the pair the RUNTIME ORACLE weighs (the
        # frozen pick plus the item the learned prior substitutes, and the
        # head's own preference outside the tie window) instead of only the
        # candidates the coverage work order happens to flag. Measured on the
        # first on-policy batch: 76 of 225 sampled decisions carried a
        # pick+alternative pair, which is the row shape the offline
        # `intervention` report needs and `coverage` mode never produced.
        "--candidate-mode", "$CandidateMode",
        "--out-tag", "$itTag") `
        -Next "if this stage died, only the partially written rows are lost; the rest are valid, and a re-run with -Force continues from seed-start" | Out-Null

    # --- 3. refit on every iteration to date --------------------------------
    $train = Get-DecisionFiles -Split "train"
    $hold = Get-DecisionFiles -Split "holdout"
    Invoke-Stage -Name "${itTag}_fit" -SkipIf "results/value_model_report_$itTag.json" -Command @(
        "python", "tools/fit_value_model.py",
        "--train", $train, "--holdout", $hold,
        "--out", "vendor/balatro-rl/balatro_sim/value_tables.json",
        "--report", "results/value_model_report_$itTag.json") `
        -Next "read within-decision concordance and selection ctx_delta in the report; promote an arm only on a positive paired net" | Out-Null

    # --- 4. work order for the NEXT iteration -------------------------------
    Invoke-Stage -Name "${itTag}_audit_post" -SkipIf "results/coverage_focus_$($Tag)$($i + 1).json" -Command @(
        "python", "tools/audit_value_coverage.py",
        "--census", "results/offer_census.json",
        "--focus-out", "results/coverage_focus_$($Tag)$($i + 1).json") `
        -Next "this is the next round's work order" | Out-Null

    # --- 5. paired behaviour screen -----------------------------------------
    $screenOut = ""
    if (-not $SkipScreen -and $ScreenSeeds -gt 0) {
        $screenOut = "results/screen_$itTag.json"
        Invoke-Stage -Name "${itTag}_screen" -SkipIf $screenOut -Command @(
            "python", "bench/bench_v11_ablation.py",
            "--seeds", "10500-$([int](10500 + $ScreenSeeds - 1))",
            "--variants", $Variants,
            "--workers", "$([math]::Max(2, $Workers - 8))",
            "--out", $screenOut) `
            -Next "if one arm beats __v10__ with a positive paired net, replicate it on a fresh seed bank before promoting the margin" | Out-Null
    }

    Add-Ledger -Entry @{
        id = "$itTag"; kind = "iterate-loop"; stage = "round-complete"
        command = "tools/iterate.ps1 -Iterations $Iterations -SeedStart $SeedStart (round $i/$Iterations)"
        seeds = "$seed0..$($seed0 + $SeedsPerIteration - 1)"
        budget_min = $BudgetMinutes; workers = $Workers
        result = "collect+fit+audit complete; screen=$screenOut (arm results in the screen JSON)"
        artifact = @(
            "results/coverage_focus_$($Tag)$($i + 1).json",
            "results/value_model_report_$itTag.json",
            "results/decisions/train_$itTag.jsonl",
            "vendor/balatro-rl/balatro_sim/value_tables.json") -join " "
        next = "after the last round: read the screen JSON, and if one prior arm beats __v10__ with a positive paired net, promote the margin; else apply the coverage audit's remaining work order with another round"
    }
}

Write-Heartbeat -Stage "all-rounds" -Status "ok"
Write-Host ""
Write-Host "iterate.ps1: $Iterations round(s) complete. Ledger: logs_sim/runs.jsonl"
